/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bootstrap/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBootstrapStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bootstrap/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateBootstrapCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bootstrap/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startBootstrap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bootstrap/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyBootstrap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startMagicAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyMagicAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-requests/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAccessRequestStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateMe"];
        trace?: never;
    };
    "/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updatePreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lookupUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createFolder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeID"];
            };
            cookie?: never;
        };
        get: operations["getNode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateNode"];
        trace?: never;
    };
    "/nodes/{nodeId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["moveNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{nodeId}/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["copyNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{nodeId}/save-copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["saveSharedFileCopy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{nodeId}/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["trashNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{nodeId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{nodeId}/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["purgeNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bulkMutateNodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["downloadNodeArchive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{nodeId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{nodeId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFileVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{nodeId}/versions/{versionId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreFileVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchNodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRecentNodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFavorites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["addFavorite"];
        post?: never;
        delete: operations["removeFavorite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTrash"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shared": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSharedWithMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{uploadId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uploadId: components["parameters"]["UploadID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["cancelUpload"];
        options?: never;
        head: operations["inspectUpload"];
        patch: operations["appendUpload"];
        trace?: never;
    };
    "/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInternalShares"];
        put?: never;
        post: operations["createInternalShare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shares/{shareId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeInternalShare"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public-shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublicShares"];
        put?: never;
        post: operations["createPublicShare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public-shares/{shareId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokePublicShare"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exchangePublicCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicBundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadPublicArchive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/files/{nodeId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadPublicFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTokens"];
        put?: never;
        post: operations["createToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/support-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getActiveSupportAccess"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/support-access/{accessId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["endSupportAccess"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListUsers"];
        put?: never;
        post: operations["adminCreateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["adminUpdateUser"];
        trace?: never;
    };
    "/admin/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/requests/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminDecideRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetStorage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/jobs/{jobId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminRetryJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetSettings"];
        put: operations["adminUpdateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/policies/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetPolicy"];
        put: operations["adminUpdatePolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/support-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminStartSupportAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            /** Format: email */
            email: string;
            display_name?: string;
            /** @enum {string} */
            role: "superadmin" | "member";
            /** @enum {string} */
            state: "provisioning" | "active" | "suspended" | "over_quota" | "deletion_pending" | "deleted";
            /** Format: int64 */
            quota_bytes: number;
            quota_unlimited?: boolean;
            /** Format: int64 */
            used_bytes: number;
            /** Format: int64 */
            reserved_bytes: number;
            preferences?: components["schemas"]["Preferences"];
        };
        Preferences: {
            /** @enum {string} */
            theme_mode?: "system" | "light" | "dark";
            accent?: string;
            /** @enum {string} */
            density?: "compact" | "comfortable";
            reduced_motion?: boolean;
        };
        Node: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            parent_id?: string | null;
            /** Format: uuid */
            owner_id: string;
            /** @enum {string} */
            kind: "file" | "folder";
            name: string;
            mime_type?: string;
            /** Format: int64 */
            size_bytes: number;
            /** Format: int64 */
            revision: number;
            /** Format: uuid */
            current_version_id?: string;
            capabilities?: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        FileVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            node_id: string;
            /** Format: int64 */
            sequence: number;
            /** Format: int64 */
            size_bytes: number;
            sha256: string;
            mime_type: string;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
        };
        Share: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            permission: "viewer" | "editor";
            roots: components["schemas"]["Node"][];
            recipients: components["schemas"]["User"][];
            /** Format: date-time */
            expires_at?: string | null;
            allow_editor_uploads?: boolean;
            /** Format: int64 */
            editor_byte_allowance?: number | null;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PublicShare: {
            /** Format: uuid */
            id: string;
            roots: components["schemas"]["Node"][];
            /** Format: date-time */
            expires_at: string;
            redemption_limit: number;
            redemption_count: number;
            /** @enum {string} */
            state: "active" | "expired" | "exhausted" | "revoked";
            /** Format: date-time */
            created_at: string;
        };
        Upload: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            state: "pending" | "receiving" | "finalizing" | "completed" | "cancelled" | "expired" | "failed";
            /** Format: int64 */
            expected_bytes: number;
            /** Format: int64 */
            committed_bytes: number;
            /** Format: date-time */
            expires_at: string;
            /** Format: uuid */
            parent_id: string;
            filename: string;
            /** @enum {string} */
            conflict_mode: "error" | "keep_both" | "replace";
            /** Format: uuid */
            node_id?: string | null;
            /** Format: uuid */
            current_version_id?: string | null;
        };
        Policy: {
            /** Format: int64 */
            quota_bytes: number;
            unlimited: boolean;
            /** Format: int64 */
            max_file_bytes?: number;
            /** Format: int64 */
            max_items?: number;
            allow_internal_sharing: boolean;
            allow_public_sharing: boolean;
            allow_api_tokens: boolean;
            max_concurrent_uploads?: number;
            max_pending_uploads?: number;
            max_active_public_shares?: number;
            max_public_ttl_minutes?: number;
            max_public_redemptions?: number;
            blocked_extensions?: string[];
        };
        Session: {
            authenticated: boolean;
            user?: components["schemas"]["User"];
            csrf_token?: string;
        };
        List: {
            items: {
                [key: string]: unknown;
            }[];
            next_cursor?: string | null;
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            code: string;
            request_id: string;
            retry_after?: number;
            field_errors?: {
                [key: string]: string;
            };
        };
    };
    responses: {
        /** @description Successful JSON response */
        JSON: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Paginated list */
        List: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["List"];
            };
        };
        /** @description Node */
        Node: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Node"];
            };
        };
        /** @description User */
        User: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["User"];
            };
        };
        /** @description Upload */
        Upload: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Upload"];
            };
        };
        /** @description File version */
        FileVersion: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["FileVersion"];
            };
        };
        /** @description User policy */
        Policy: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Policy"];
            };
        };
        /** @description Session */
        Session: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Session"];
            };
        };
        /** @description Bootstrap state */
        BootstrapStatus: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    initialized: boolean;
                    setup_required?: boolean;
                    /** Format: date-time */
                    expires_at?: string;
                };
            };
        };
        /** @description Problem detail */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        NodeID: string;
        UploadID: string;
        ShareID: string;
        Cursor: string;
        Limit: number;
        Query: string;
        IfMatch: string;
        IdempotencyKey: string;
    };
    requestBodies: {
        JSON: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBootstrapStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BootstrapStatus"];
        };
    };
    validateBootstrapCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            200: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    startBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            202: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    verifyBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            200: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    startMagicAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            202: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    verifyMagicAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Session"];
            default: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Session"];
            default: components["responses"]["Problem"];
        };
    };
    requestAccess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            202: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    getAccessRequestStatus: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["User"];
            default: components["responses"]["Problem"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            200: components["responses"]["User"];
            default: components["responses"]["Problem"];
        };
    };
    updatePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            200: components["responses"]["User"];
            default: components["responses"]["Problem"];
        };
    };
    lookupUsers: {
        parameters: {
            query: {
                q: components["parameters"]["Query"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    listNodes: {
        parameters: {
            query?: {
                parent_id?: string;
                /** @description Target user for an active audited support session. */
                support_user?: string;
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    createFolder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            201: components["responses"]["Node"];
            default: components["responses"]["Problem"];
        };
    };
    getNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Node"];
            default: components["responses"]["Problem"];
        };
    };
    updateNode: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                nodeId: components["parameters"]["NodeID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            200: components["responses"]["Node"];
            default: components["responses"]["Problem"];
        };
    };
    moveNode: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                nodeId: components["parameters"]["NodeID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            200: components["responses"]["Node"];
            default: components["responses"]["Problem"];
        };
    };
    copyNode: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                nodeId: components["parameters"]["NodeID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            201: components["responses"]["Node"];
            default: components["responses"]["Problem"];
        };
    };
    saveSharedFileCopy: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                nodeId: components["parameters"]["NodeID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            201: components["responses"]["Upload"];
            default: components["responses"]["Problem"];
        };
    };
    trashNode: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                nodeId: components["parameters"]["NodeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Node"];
            default: components["responses"]["Problem"];
        };
    };
    restoreNode: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                nodeId: components["parameters"]["NodeID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            200: components["responses"]["Node"];
            default: components["responses"]["Problem"];
        };
    };
    purgeNode: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                nodeId: components["parameters"]["NodeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    bulkMutateNodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            200: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    downloadNodeArchive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            /** @description Streamed ZIP64 archive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    downloadFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Partial file stream */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listFileVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    restoreFileVersion: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                nodeId: components["parameters"]["NodeID"];
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: components["responses"]["FileVersion"];
            default: components["responses"]["Problem"];
        };
    };
    searchNodes: {
        parameters: {
            query: {
                q: components["parameters"]["Query"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    listRecentNodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    listFavorites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    addFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Favorite added */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    removeFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Favorite removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listTrash: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    listSharedWithMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    createUpload: {
        parameters: {
            query?: never;
            header: {
                "Upload-Length": number;
                "Upload-Metadata": string;
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload created */
            201: {
                headers: {
                    Location?: string;
                    "Tus-Resumable"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    cancelUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uploadId: components["parameters"]["UploadID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload cancelled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    inspectUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uploadId: components["parameters"]["UploadID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current upload offset */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    appendUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uploadId: components["parameters"]["UploadID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/offset+octet-stream": string;
            };
        };
        responses: {
            /** @description Chunk committed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listInternalShares: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    createInternalShare: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            201: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    revokeInternalShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shareId: components["parameters"]["ShareID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Share revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listPublicShares: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    createPublicShare: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            201: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    revokePublicShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shareId: components["parameters"]["ShareID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Share revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    exchangePublicCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                };
            };
        };
        responses: {
            200: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    getPublicBundle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    downloadPublicArchive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Streamed ZIP64 public bundle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    downloadPublicFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public file stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Partial public file stream */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    createToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            201: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    revokeToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    getActiveSupportAccess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    endSupportAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accessId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Support access ended */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    adminListUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    adminCreateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            201: components["responses"]["User"];
            default: components["responses"]["Problem"];
        };
    };
    adminUpdateUser: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            200: components["responses"]["User"];
            default: components["responses"]["Problem"];
        };
    };
    adminListRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    adminDecideRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            200: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    adminGetStorage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    adminListJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    adminRetryJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job requeued */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    adminListAuditEvents: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                format?: "json" | "csv";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    adminGetSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    adminUpdateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            200: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    adminGetPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Policy"];
            default: components["responses"]["Problem"];
        };
    };
    adminUpdatePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            200: components["responses"]["Policy"];
            default: components["responses"]["Problem"];
        };
    };
    adminStartSupportAccess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            201: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
}
