/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bootstrap/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBootstrapStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bootstrap/configure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["configureBootstrap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bootstrap/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyBootstrap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startMagicAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyMagicAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-requests/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getAccessRequestStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updatePreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lookupUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createFolder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeID"];
            };
            cookie?: never;
        };
        get: operations["getNode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateNode"];
        trace?: never;
    };
    "/nodes/{nodeId}/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeID"];
                action: "move" | "copy" | "trash" | "restore" | "purge";
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mutateNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bulkMutateNodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{nodeId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{nodeId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFileVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchNodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRecentNodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFavorites"];
        put?: never;
        post: operations["addFavorite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{uploadId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uploadId: components["parameters"]["UploadID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["cancelUpload"];
        options?: never;
        head: operations["inspectUpload"];
        patch: operations["appendUpload"];
        trace?: never;
    };
    "/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInternalShares"];
        put?: never;
        post: operations["createInternalShare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shares/{shareId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeInternalShare"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public-shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPublicShare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public-shares/{shareId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokePublicShare"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exchangePublicCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicBundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTokens"];
        put?: never;
        post: operations["createToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListUsers"];
        put?: never;
        post: operations["adminCreateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["adminUpdateUser"];
        trace?: never;
    };
    "/admin/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/requests/{requestId}/{decision}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminDecideRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/{resource}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetResource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            /** Format: email */
            email: string;
            display_name?: string;
            /** @enum {string} */
            role: "superadmin" | "member";
            /** @enum {string} */
            state: "provisioning" | "active" | "suspended" | "over_quota" | "deletion_pending" | "deleted";
            /** Format: int64 */
            quota_bytes: number;
            quota_unlimited?: boolean;
            /** Format: int64 */
            used_bytes: number;
            /** Format: int64 */
            reserved_bytes: number;
            preferences?: components["schemas"]["Preferences"];
        };
        Preferences: {
            /** @enum {string} */
            theme_mode?: "system" | "light" | "dark";
            accent?: string;
            /** @enum {string} */
            density?: "compact" | "comfortable";
            reduced_motion?: boolean;
        };
        Node: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            parent_id?: string | null;
            /** Format: uuid */
            owner_id: string;
            /** @enum {string} */
            kind: "file" | "folder";
            name: string;
            mime_type?: string;
            /** Format: int64 */
            size_bytes: number;
            /** Format: int64 */
            revision: number;
            /** Format: uuid */
            current_version_id?: string;
            capabilities?: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Session: {
            authenticated: boolean;
            user?: components["schemas"]["User"];
            csrf_token?: string;
        };
        List: {
            items: {
                [key: string]: unknown;
            }[];
            next_cursor?: string | null;
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            code: string;
            request_id: string;
            retry_after?: number;
            field_errors?: {
                [key: string]: string;
            };
        };
    };
    responses: {
        /** @description Successful JSON response */
        JSON: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Paginated list */
        List: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["List"];
            };
        };
        /** @description Node */
        Node: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Node"];
            };
        };
        /** @description User */
        User: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["User"];
            };
        };
        /** @description Session */
        Session: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Session"];
            };
        };
        /** @description Bootstrap state */
        BootstrapStatus: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    initialized: boolean;
                    setup_required?: boolean;
                    /** Format: date-time */
                    expires_at?: string;
                };
            };
        };
        /** @description Problem detail */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        NodeID: string;
        UploadID: string;
        ShareID: string;
        Cursor: string;
        Limit: number;
        Query: string;
        IfMatch: string;
        IdempotencyKey: string;
    };
    requestBodies: {
        JSON: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBootstrapStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BootstrapStatus"];
        };
    };
    configureBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            200: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    verifyBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            200: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    startMagicAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            202: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    verifyMagicAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Session"];
            default: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Session"];
            default: components["responses"]["Problem"];
        };
    };
    requestAccess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            202: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    getAccessRequestStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            200: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["User"];
            default: components["responses"]["Problem"];
        };
    };
    updatePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            200: components["responses"]["User"];
            default: components["responses"]["Problem"];
        };
    };
    lookupUsers: {
        parameters: {
            query: {
                q: components["parameters"]["Query"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    listNodes: {
        parameters: {
            query?: {
                parent_id?: string;
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    createFolder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            201: components["responses"]["Node"];
            default: components["responses"]["Problem"];
        };
    };
    getNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Node"];
            default: components["responses"]["Problem"];
        };
    };
    updateNode: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                nodeId: components["parameters"]["NodeID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            200: components["responses"]["Node"];
            default: components["responses"]["Problem"];
        };
    };
    mutateNode: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                nodeId: components["parameters"]["NodeID"];
                action: "move" | "copy" | "trash" | "restore" | "purge";
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            200: components["responses"]["JSON"];
            /** @description Completed without a representation */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    bulkMutateNodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            200: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    downloadFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Partial file stream */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listFileVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    searchNodes: {
        parameters: {
            query: {
                q: components["parameters"]["Query"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    listRecentNodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    listFavorites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    addFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            /** @description Favorite added */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    createUpload: {
        parameters: {
            query?: never;
            header: {
                "Upload-Length": number;
                "Upload-Metadata": string;
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload created */
            201: {
                headers: {
                    Location?: string;
                    "Tus-Resumable"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    cancelUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uploadId: components["parameters"]["UploadID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload cancelled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    inspectUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uploadId: components["parameters"]["UploadID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current upload offset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    appendUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uploadId: components["parameters"]["UploadID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/offset+octet-stream": string;
            };
        };
        responses: {
            /** @description Chunk committed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listInternalShares: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    createInternalShare: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            201: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    revokeInternalShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shareId: components["parameters"]["ShareID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Share revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    createPublicShare: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            201: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    revokePublicShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shareId: components["parameters"]["ShareID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Share revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    exchangePublicCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                };
            };
        };
        responses: {
            200: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    getPublicBundle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    listTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    createToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            201: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    revokeToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    adminListUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    adminCreateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            201: components["responses"]["User"];
            default: components["responses"]["Problem"];
        };
    };
    adminUpdateUser: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            200: components["responses"]["User"];
            default: components["responses"]["Problem"];
        };
    };
    adminListRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["List"];
            default: components["responses"]["Problem"];
        };
    };
    adminDecideRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: string;
                decision: "approve" | "reject";
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JSON"];
        responses: {
            200: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
    adminGetResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource: "storage" | "policies" | "jobs" | "audit" | "settings";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JSON"];
            default: components["responses"]["Problem"];
        };
    };
}
