// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package apitypes

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for NodeKind.
const (
	File   NodeKind = "file"
	Folder NodeKind = "folder"
)

// Defines values for PreferencesDensity.
const (
	Comfortable PreferencesDensity = "comfortable"
	Compact     PreferencesDensity = "compact"
)

// Defines values for PreferencesThemeMode.
const (
	Dark   PreferencesThemeMode = "dark"
	Light  PreferencesThemeMode = "light"
	System PreferencesThemeMode = "system"
)

// Defines values for UserRole.
const (
	Member     UserRole = "member"
	Superadmin UserRole = "superadmin"
)

// Defines values for UserState.
const (
	Active          UserState = "active"
	Deleted         UserState = "deleted"
	DeletionPending UserState = "deletion_pending"
	OverQuota       UserState = "over_quota"
	Provisioning    UserState = "provisioning"
	Suspended       UserState = "suspended"
)

// Defines values for AdminDecideRequestParamsDecision.
const (
	Approve AdminDecideRequestParamsDecision = "approve"
	Reject  AdminDecideRequestParamsDecision = "reject"
)

// Defines values for AdminGetResourceParamsResource.
const (
	Audit    AdminGetResourceParamsResource = "audit"
	Jobs     AdminGetResourceParamsResource = "jobs"
	Policies AdminGetResourceParamsResource = "policies"
	Settings AdminGetResourceParamsResource = "settings"
	Storage  AdminGetResourceParamsResource = "storage"
)

// List defines model for List.
type List struct {
	Items      []map[string]interface{} `json:"items"`
	NextCursor *string                  `json:"next_cursor"`
}

// Node defines model for Node.
type Node struct {
	Capabilities     *[]string           `json:"capabilities,omitempty"`
	CreatedAt        time.Time           `json:"created_at"`
	CurrentVersionId *openapi_types.UUID `json:"current_version_id,omitempty"`
	Id               openapi_types.UUID  `json:"id"`
	Kind             NodeKind            `json:"kind"`
	MimeType         *string             `json:"mime_type,omitempty"`
	Name             string              `json:"name"`
	OwnerId          openapi_types.UUID  `json:"owner_id"`
	ParentId         *openapi_types.UUID `json:"parent_id"`
	Revision         int64               `json:"revision"`
	SizeBytes        int64               `json:"size_bytes"`
	UpdatedAt        time.Time           `json:"updated_at"`
}

// NodeKind defines model for Node.Kind.
type NodeKind string

// Preferences defines model for Preferences.
type Preferences struct {
	Accent        *string               `json:"accent,omitempty"`
	Density       *PreferencesDensity   `json:"density,omitempty"`
	ReducedMotion *bool                 `json:"reduced_motion,omitempty"`
	ThemeMode     *PreferencesThemeMode `json:"theme_mode,omitempty"`
}

// PreferencesDensity defines model for Preferences.Density.
type PreferencesDensity string

// PreferencesThemeMode defines model for Preferences.ThemeMode.
type PreferencesThemeMode string

// Problem defines model for Problem.
type Problem struct {
	Code        string             `json:"code"`
	Detail      *string            `json:"detail,omitempty"`
	FieldErrors *map[string]string `json:"field_errors,omitempty"`
	RequestId   string             `json:"request_id"`
	RetryAfter  *int               `json:"retry_after,omitempty"`
	Status      int                `json:"status"`
	Title       string             `json:"title"`
	Type        string             `json:"type"`
}

// Session defines model for Session.
type Session struct {
	Authenticated bool    `json:"authenticated"`
	CsrfToken     *string `json:"csrf_token,omitempty"`
	User          *User   `json:"user,omitempty"`
}

// User defines model for User.
type User struct {
	DisplayName    *string             `json:"display_name,omitempty"`
	Email          openapi_types.Email `json:"email"`
	Id             openapi_types.UUID  `json:"id"`
	Preferences    *Preferences        `json:"preferences,omitempty"`
	QuotaBytes     int64               `json:"quota_bytes"`
	QuotaUnlimited *bool               `json:"quota_unlimited,omitempty"`
	ReservedBytes  int64               `json:"reserved_bytes"`
	Role           UserRole            `json:"role"`
	State          UserState           `json:"state"`
	UsedBytes      int64               `json:"used_bytes"`
	Username       string              `json:"username"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserState defines model for User.State.
type UserState string

// Cursor defines model for Cursor.
type Cursor = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// IfMatch defines model for IfMatch.
type IfMatch = string

// Limit defines model for Limit.
type Limit = int

// NodeID defines model for NodeID.
type NodeID = openapi_types.UUID

// Query defines model for Query.
type Query = string

// ShareID defines model for ShareID.
type ShareID = openapi_types.UUID

// UploadID defines model for UploadID.
type UploadID = openapi_types.UUID

// BootstrapStatus defines model for BootstrapStatus.
type BootstrapStatus struct {
	ExpiresAt     *time.Time `json:"expires_at,omitempty"`
	Initialized   bool       `json:"initialized"`
	SetupRequired *bool      `json:"setup_required,omitempty"`
}

// JSON defines model for JSON.
type JSON map[string]interface{}

// RequestAccessJSONBody defines parameters for RequestAccess.
type RequestAccessJSONBody map[string]interface{}

// GetAccessRequestStatusJSONBody defines parameters for GetAccessRequestStatus.
type GetAccessRequestStatusJSONBody map[string]interface{}

// AdminDecideRequestJSONBody defines parameters for AdminDecideRequest.
type AdminDecideRequestJSONBody map[string]interface{}

// AdminDecideRequestParamsDecision defines parameters for AdminDecideRequest.
type AdminDecideRequestParamsDecision string

// AdminCreateUserJSONBody defines parameters for AdminCreateUser.
type AdminCreateUserJSONBody map[string]interface{}

// AdminUpdateUserJSONBody defines parameters for AdminUpdateUser.
type AdminUpdateUserJSONBody map[string]interface{}

// AdminUpdateUserParams defines parameters for AdminUpdateUser.
type AdminUpdateUserParams struct {
	IfMatch IfMatch `json:"If-Match"`
}

// AdminGetResourceParamsResource defines parameters for AdminGetResource.
type AdminGetResourceParamsResource string

// StartMagicAuthJSONBody defines parameters for StartMagicAuth.
type StartMagicAuthJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// VerifyMagicAuthJSONBody defines parameters for VerifyMagicAuth.
type VerifyMagicAuthJSONBody struct {
	Code string `json:"code"`
}

// ConfigureBootstrapJSONBody defines parameters for ConfigureBootstrap.
type ConfigureBootstrapJSONBody map[string]interface{}

// VerifyBootstrapJSONBody defines parameters for VerifyBootstrap.
type VerifyBootstrapJSONBody map[string]interface{}

// AddFavoriteJSONBody defines parameters for AddFavorite.
type AddFavoriteJSONBody map[string]interface{}

// CreateFolderJSONBody defines parameters for CreateFolder.
type CreateFolderJSONBody map[string]interface{}

// UpdatePreferencesJSONBody defines parameters for UpdatePreferences.
type UpdatePreferencesJSONBody map[string]interface{}

// ListNodesParams defines parameters for ListNodes.
type ListNodesParams struct {
	ParentId *openapi_types.UUID `form:"parent_id,omitempty" json:"parent_id,omitempty"`
	Cursor   *Cursor             `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit    *Limit              `form:"limit,omitempty" json:"limit,omitempty"`
}

// BulkMutateNodesJSONBody defines parameters for BulkMutateNodes.
type BulkMutateNodesJSONBody map[string]interface{}

// UpdateNodeJSONBody defines parameters for UpdateNode.
type UpdateNodeJSONBody map[string]interface{}

// UpdateNodeParams defines parameters for UpdateNode.
type UpdateNodeParams struct {
	IfMatch IfMatch `json:"If-Match"`
}

// MutateNodeJSONBody defines parameters for MutateNode.
type MutateNodeJSONBody map[string]interface{}

// MutateNodeParams defines parameters for MutateNode.
type MutateNodeParams struct {
	IfMatch IfMatch `json:"If-Match"`
}

// CreatePublicShareJSONBody defines parameters for CreatePublicShare.
type CreatePublicShareJSONBody map[string]interface{}

// CreatePublicShareParams defines parameters for CreatePublicShare.
type CreatePublicShareParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ExchangePublicCodeJSONBody defines parameters for ExchangePublicCode.
type ExchangePublicCodeJSONBody struct {
	Code string `json:"code"`
}

// SearchNodesParams defines parameters for SearchNodes.
type SearchNodesParams struct {
	Q     Query  `form:"q" json:"q"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateInternalShareJSONBody defines parameters for CreateInternalShare.
type CreateInternalShareJSONBody map[string]interface{}

// CreateInternalShareParams defines parameters for CreateInternalShare.
type CreateInternalShareParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateTokenJSONBody defines parameters for CreateToken.
type CreateTokenJSONBody map[string]interface{}

// CreateUploadParams defines parameters for CreateUpload.
type CreateUploadParams struct {
	UploadLength   int64          `json:"Upload-Length"`
	UploadMetadata string         `json:"Upload-Metadata"`
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// LookupUsersParams defines parameters for LookupUsers.
type LookupUsersParams struct {
	Q Query `form:"q" json:"q"`
}

// RequestAccessJSONRequestBody defines body for RequestAccess for application/json ContentType.
type RequestAccessJSONRequestBody RequestAccessJSONBody

// GetAccessRequestStatusJSONRequestBody defines body for GetAccessRequestStatus for application/json ContentType.
type GetAccessRequestStatusJSONRequestBody GetAccessRequestStatusJSONBody

// AdminDecideRequestJSONRequestBody defines body for AdminDecideRequest for application/json ContentType.
type AdminDecideRequestJSONRequestBody AdminDecideRequestJSONBody

// AdminCreateUserJSONRequestBody defines body for AdminCreateUser for application/json ContentType.
type AdminCreateUserJSONRequestBody AdminCreateUserJSONBody

// AdminUpdateUserJSONRequestBody defines body for AdminUpdateUser for application/json ContentType.
type AdminUpdateUserJSONRequestBody AdminUpdateUserJSONBody

// StartMagicAuthJSONRequestBody defines body for StartMagicAuth for application/json ContentType.
type StartMagicAuthJSONRequestBody StartMagicAuthJSONBody

// VerifyMagicAuthJSONRequestBody defines body for VerifyMagicAuth for application/json ContentType.
type VerifyMagicAuthJSONRequestBody VerifyMagicAuthJSONBody

// ConfigureBootstrapJSONRequestBody defines body for ConfigureBootstrap for application/json ContentType.
type ConfigureBootstrapJSONRequestBody ConfigureBootstrapJSONBody

// VerifyBootstrapJSONRequestBody defines body for VerifyBootstrap for application/json ContentType.
type VerifyBootstrapJSONRequestBody VerifyBootstrapJSONBody

// AddFavoriteJSONRequestBody defines body for AddFavorite for application/json ContentType.
type AddFavoriteJSONRequestBody AddFavoriteJSONBody

// CreateFolderJSONRequestBody defines body for CreateFolder for application/json ContentType.
type CreateFolderJSONRequestBody CreateFolderJSONBody

// UpdatePreferencesJSONRequestBody defines body for UpdatePreferences for application/json ContentType.
type UpdatePreferencesJSONRequestBody UpdatePreferencesJSONBody

// BulkMutateNodesJSONRequestBody defines body for BulkMutateNodes for application/json ContentType.
type BulkMutateNodesJSONRequestBody BulkMutateNodesJSONBody

// UpdateNodeJSONRequestBody defines body for UpdateNode for application/json ContentType.
type UpdateNodeJSONRequestBody UpdateNodeJSONBody

// MutateNodeJSONRequestBody defines body for MutateNode for application/json ContentType.
type MutateNodeJSONRequestBody MutateNodeJSONBody

// CreatePublicShareJSONRequestBody defines body for CreatePublicShare for application/json ContentType.
type CreatePublicShareJSONRequestBody CreatePublicShareJSONBody

// ExchangePublicCodeJSONRequestBody defines body for ExchangePublicCode for application/json ContentType.
type ExchangePublicCodeJSONRequestBody ExchangePublicCodeJSONBody

// CreateInternalShareJSONRequestBody defines body for CreateInternalShare for application/json ContentType.
type CreateInternalShareJSONRequestBody CreateInternalShareJSONBody

// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody CreateTokenJSONBody
