// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package apitypes

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for NodeKind.
const (
	File   NodeKind = "file"
	Folder NodeKind = "folder"
)

// Defines values for PreferencesDensity.
const (
	Comfortable PreferencesDensity = "comfortable"
	Compact     PreferencesDensity = "compact"
)

// Defines values for PreferencesThemeMode.
const (
	Dark   PreferencesThemeMode = "dark"
	Light  PreferencesThemeMode = "light"
	System PreferencesThemeMode = "system"
)

// Defines values for PublicShareState.
const (
	PublicShareStateActive    PublicShareState = "active"
	PublicShareStateExhausted PublicShareState = "exhausted"
	PublicShareStateExpired   PublicShareState = "expired"
	PublicShareStateRevoked   PublicShareState = "revoked"
)

// Defines values for SharePermission.
const (
	Editor SharePermission = "editor"
	Viewer SharePermission = "viewer"
)

// Defines values for UploadConflictMode.
const (
	Error    UploadConflictMode = "error"
	KeepBoth UploadConflictMode = "keep_both"
	Replace  UploadConflictMode = "replace"
)

// Defines values for UploadState.
const (
	UploadStateCancelled  UploadState = "cancelled"
	UploadStateCompleted  UploadState = "completed"
	UploadStateExpired    UploadState = "expired"
	UploadStateFailed     UploadState = "failed"
	UploadStateFinalizing UploadState = "finalizing"
	UploadStatePending    UploadState = "pending"
	UploadStateReceiving  UploadState = "receiving"
)

// Defines values for UserRole.
const (
	Member     UserRole = "member"
	Superadmin UserRole = "superadmin"
)

// Defines values for UserState.
const (
	Active          UserState = "active"
	Deleted         UserState = "deleted"
	DeletionPending UserState = "deletion_pending"
	OverQuota       UserState = "over_quota"
	Provisioning    UserState = "provisioning"
	Suspended       UserState = "suspended"
)

// Defines values for AdminListAuditEventsParamsFormat.
const (
	Csv  AdminListAuditEventsParamsFormat = "csv"
	Json AdminListAuditEventsParamsFormat = "json"
)

// FileVersion defines model for FileVersion.
type FileVersion struct {
	CreatedAt time.Time          `json:"created_at"`
	CreatedBy openapi_types.UUID `json:"created_by"`
	Id        openapi_types.UUID `json:"id"`
	MimeType  string             `json:"mime_type"`
	NodeId    openapi_types.UUID `json:"node_id"`
	Sequence  int64              `json:"sequence"`
	Sha256    string             `json:"sha256"`
	SizeBytes int64              `json:"size_bytes"`
}

// List defines model for List.
type List struct {
	Items      []map[string]interface{} `json:"items"`
	NextCursor *string                  `json:"next_cursor"`
}

// Node defines model for Node.
type Node struct {
	Capabilities     *[]string           `json:"capabilities,omitempty"`
	CreatedAt        time.Time           `json:"created_at"`
	CurrentVersionId *openapi_types.UUID `json:"current_version_id,omitempty"`
	Id               openapi_types.UUID  `json:"id"`
	Kind             NodeKind            `json:"kind"`
	MimeType         *string             `json:"mime_type,omitempty"`
	Name             string              `json:"name"`
	OwnerId          openapi_types.UUID  `json:"owner_id"`
	ParentId         *openapi_types.UUID `json:"parent_id"`
	Revision         int64               `json:"revision"`
	SizeBytes        int64               `json:"size_bytes"`
	UpdatedAt        time.Time           `json:"updated_at"`
}

// NodeKind defines model for Node.Kind.
type NodeKind string

// Policy defines model for Policy.
type Policy struct {
	AllowApiTokens        bool      `json:"allow_api_tokens"`
	AllowInternalSharing  bool      `json:"allow_internal_sharing"`
	AllowPublicSharing    bool      `json:"allow_public_sharing"`
	BlockedExtensions     *[]string `json:"blocked_extensions,omitempty"`
	MaxActivePublicShares *int      `json:"max_active_public_shares,omitempty"`
	MaxConcurrentUploads  *int      `json:"max_concurrent_uploads,omitempty"`
	MaxFileBytes          *int64    `json:"max_file_bytes,omitempty"`
	MaxItems              *int64    `json:"max_items,omitempty"`
	MaxPendingUploads     *int      `json:"max_pending_uploads,omitempty"`
	MaxPublicRedemptions  *int      `json:"max_public_redemptions,omitempty"`
	MaxPublicTtlMinutes   *int      `json:"max_public_ttl_minutes,omitempty"`
	QuotaBytes            int64     `json:"quota_bytes"`
	Unlimited             bool      `json:"unlimited"`
}

// Preferences defines model for Preferences.
type Preferences struct {
	Accent        *string               `json:"accent,omitempty"`
	Density       *PreferencesDensity   `json:"density,omitempty"`
	ReducedMotion *bool                 `json:"reduced_motion,omitempty"`
	ThemeMode     *PreferencesThemeMode `json:"theme_mode,omitempty"`
}

// PreferencesDensity defines model for Preferences.Density.
type PreferencesDensity string

// PreferencesThemeMode defines model for Preferences.ThemeMode.
type PreferencesThemeMode string

// Problem defines model for Problem.
type Problem struct {
	Code        string             `json:"code"`
	Detail      *string            `json:"detail,omitempty"`
	FieldErrors *map[string]string `json:"field_errors,omitempty"`
	RequestId   string             `json:"request_id"`
	RetryAfter  *int               `json:"retry_after,omitempty"`
	Status      int                `json:"status"`
	Title       string             `json:"title"`
	Type        string             `json:"type"`
}

// PublicShare defines model for PublicShare.
type PublicShare struct {
	CreatedAt       time.Time          `json:"created_at"`
	ExpiresAt       time.Time          `json:"expires_at"`
	Id              openapi_types.UUID `json:"id"`
	RedemptionCount int                `json:"redemption_count"`
	RedemptionLimit int                `json:"redemption_limit"`
	Roots           []Node             `json:"roots"`
	State           PublicShareState   `json:"state"`
}

// PublicShareState defines model for PublicShare.State.
type PublicShareState string

// Session defines model for Session.
type Session struct {
	Authenticated bool    `json:"authenticated"`
	CsrfToken     *string `json:"csrf_token,omitempty"`
	User          *User   `json:"user,omitempty"`
}

// Share defines model for Share.
type Share struct {
	AllowEditorUploads  *bool              `json:"allow_editor_uploads,omitempty"`
	CreatedAt           time.Time          `json:"created_at"`
	CreatedBy           openapi_types.UUID `json:"created_by"`
	EditorByteAllowance *int64             `json:"editor_byte_allowance"`
	ExpiresAt           *time.Time         `json:"expires_at"`
	Id                  openapi_types.UUID `json:"id"`
	Permission          SharePermission    `json:"permission"`
	Recipients          []User             `json:"recipients"`
	Roots               []Node             `json:"roots"`
	UpdatedAt           time.Time          `json:"updated_at"`
}

// SharePermission defines model for Share.Permission.
type SharePermission string

// Upload defines model for Upload.
type Upload struct {
	CommittedBytes   int64               `json:"committed_bytes"`
	ConflictMode     UploadConflictMode  `json:"conflict_mode"`
	CurrentVersionId *openapi_types.UUID `json:"current_version_id"`
	ExpectedBytes    int64               `json:"expected_bytes"`
	ExpiresAt        time.Time           `json:"expires_at"`
	Filename         string              `json:"filename"`
	Id               openapi_types.UUID  `json:"id"`
	NodeId           *openapi_types.UUID `json:"node_id"`
	ParentId         openapi_types.UUID  `json:"parent_id"`
	State            UploadState         `json:"state"`
}

// UploadConflictMode defines model for Upload.ConflictMode.
type UploadConflictMode string

// UploadState defines model for Upload.State.
type UploadState string

// User defines model for User.
type User struct {
	DisplayName    *string             `json:"display_name,omitempty"`
	Email          openapi_types.Email `json:"email"`
	Id             openapi_types.UUID  `json:"id"`
	Preferences    *Preferences        `json:"preferences,omitempty"`
	QuotaBytes     int64               `json:"quota_bytes"`
	QuotaUnlimited *bool               `json:"quota_unlimited,omitempty"`
	ReservedBytes  int64               `json:"reserved_bytes"`
	Role           UserRole            `json:"role"`
	State          UserState           `json:"state"`
	UsedBytes      int64               `json:"used_bytes"`
	Username       string              `json:"username"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserState defines model for User.State.
type UserState string

// Cursor defines model for Cursor.
type Cursor = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// IfMatch defines model for IfMatch.
type IfMatch = string

// Limit defines model for Limit.
type Limit = int

// NodeID defines model for NodeID.
type NodeID = openapi_types.UUID

// Query defines model for Query.
type Query = string

// ShareID defines model for ShareID.
type ShareID = openapi_types.UUID

// UploadID defines model for UploadID.
type UploadID = openapi_types.UUID

// BootstrapStatus defines model for BootstrapStatus.
type BootstrapStatus struct {
	ExpiresAt     *time.Time `json:"expires_at,omitempty"`
	Initialized   bool       `json:"initialized"`
	SetupRequired *bool      `json:"setup_required,omitempty"`
}

// JSON defines model for JSON.
type JSON map[string]interface{}

// RequestAccessJSONBody defines parameters for RequestAccess.
type RequestAccessJSONBody map[string]interface{}

// GetAccessRequestStatusParams defines parameters for GetAccessRequestStatus.
type GetAccessRequestStatusParams struct {
	Token string `form:"token" json:"token"`
}

// AdminListAuditEventsParams defines parameters for AdminListAuditEvents.
type AdminListAuditEventsParams struct {
	Limit  *Limit                            `form:"limit,omitempty" json:"limit,omitempty"`
	Format *AdminListAuditEventsParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// AdminListAuditEventsParamsFormat defines parameters for AdminListAuditEvents.
type AdminListAuditEventsParamsFormat string

// AdminUpdatePolicyJSONBody defines parameters for AdminUpdatePolicy.
type AdminUpdatePolicyJSONBody map[string]interface{}

// AdminDecideRequestJSONBody defines parameters for AdminDecideRequest.
type AdminDecideRequestJSONBody map[string]interface{}

// AdminUpdateSettingsJSONBody defines parameters for AdminUpdateSettings.
type AdminUpdateSettingsJSONBody map[string]interface{}

// AdminStartSupportAccessJSONBody defines parameters for AdminStartSupportAccess.
type AdminStartSupportAccessJSONBody map[string]interface{}

// AdminCreateUserJSONBody defines parameters for AdminCreateUser.
type AdminCreateUserJSONBody map[string]interface{}

// AdminUpdateUserJSONBody defines parameters for AdminUpdateUser.
type AdminUpdateUserJSONBody map[string]interface{}

// AdminUpdateUserParams defines parameters for AdminUpdateUser.
type AdminUpdateUserParams struct {
	IfMatch IfMatch `json:"If-Match"`
}

// StartMagicAuthJSONBody defines parameters for StartMagicAuth.
type StartMagicAuthJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// VerifyMagicAuthJSONBody defines parameters for VerifyMagicAuth.
type VerifyMagicAuthJSONBody struct {
	Code string `json:"code"`
}

// StartBootstrapJSONBody defines parameters for StartBootstrap.
type StartBootstrapJSONBody map[string]interface{}

// ValidateBootstrapCodeJSONBody defines parameters for ValidateBootstrapCode.
type ValidateBootstrapCodeJSONBody map[string]interface{}

// VerifyBootstrapJSONBody defines parameters for VerifyBootstrap.
type VerifyBootstrapJSONBody map[string]interface{}

// RestoreFileVersionParams defines parameters for RestoreFileVersion.
type RestoreFileVersionParams struct {
	IfMatch IfMatch `json:"If-Match"`
}

// CreateFolderJSONBody defines parameters for CreateFolder.
type CreateFolderJSONBody map[string]interface{}

// UpdateMeJSONBody defines parameters for UpdateMe.
type UpdateMeJSONBody map[string]interface{}

// UpdatePreferencesJSONBody defines parameters for UpdatePreferences.
type UpdatePreferencesJSONBody map[string]interface{}

// ListNodesParams defines parameters for ListNodes.
type ListNodesParams struct {
	ParentId *openapi_types.UUID `form:"parent_id,omitempty" json:"parent_id,omitempty"`

	// SupportUser Target user for an active audited support session.
	SupportUser *openapi_types.UUID `form:"support_user,omitempty" json:"support_user,omitempty"`
	Cursor      *Cursor             `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit       *Limit              `form:"limit,omitempty" json:"limit,omitempty"`
}

// DownloadNodeArchiveJSONBody defines parameters for DownloadNodeArchive.
type DownloadNodeArchiveJSONBody map[string]interface{}

// BulkMutateNodesJSONBody defines parameters for BulkMutateNodes.
type BulkMutateNodesJSONBody map[string]interface{}

// UpdateNodeJSONBody defines parameters for UpdateNode.
type UpdateNodeJSONBody map[string]interface{}

// UpdateNodeParams defines parameters for UpdateNode.
type UpdateNodeParams struct {
	IfMatch IfMatch `json:"If-Match"`
}

// CopyNodeJSONBody defines parameters for CopyNode.
type CopyNodeJSONBody map[string]interface{}

// CopyNodeParams defines parameters for CopyNode.
type CopyNodeParams struct {
	IfMatch        IfMatch        `json:"If-Match"`
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// MoveNodeJSONBody defines parameters for MoveNode.
type MoveNodeJSONBody map[string]interface{}

// MoveNodeParams defines parameters for MoveNode.
type MoveNodeParams struct {
	IfMatch        IfMatch        `json:"If-Match"`
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// PurgeNodeParams defines parameters for PurgeNode.
type PurgeNodeParams struct {
	IfMatch        IfMatch        `json:"If-Match"`
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// RestoreNodeJSONBody defines parameters for RestoreNode.
type RestoreNodeJSONBody map[string]interface{}

// RestoreNodeParams defines parameters for RestoreNode.
type RestoreNodeParams struct {
	IfMatch        IfMatch        `json:"If-Match"`
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// SaveSharedFileCopyJSONBody defines parameters for SaveSharedFileCopy.
type SaveSharedFileCopyJSONBody map[string]interface{}

// SaveSharedFileCopyParams defines parameters for SaveSharedFileCopy.
type SaveSharedFileCopyParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// TrashNodeParams defines parameters for TrashNode.
type TrashNodeParams struct {
	IfMatch        IfMatch        `json:"If-Match"`
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreatePublicShareJSONBody defines parameters for CreatePublicShare.
type CreatePublicShareJSONBody map[string]interface{}

// CreatePublicShareParams defines parameters for CreatePublicShare.
type CreatePublicShareParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ExchangePublicCodeJSONBody defines parameters for ExchangePublicCode.
type ExchangePublicCodeJSONBody struct {
	Code string `json:"code"`
}

// SearchNodesParams defines parameters for SearchNodes.
type SearchNodesParams struct {
	Q     Query  `form:"q" json:"q"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateInternalShareJSONBody defines parameters for CreateInternalShare.
type CreateInternalShareJSONBody map[string]interface{}

// CreateInternalShareParams defines parameters for CreateInternalShare.
type CreateInternalShareParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateTokenJSONBody defines parameters for CreateToken.
type CreateTokenJSONBody map[string]interface{}

// CreateUploadParams defines parameters for CreateUpload.
type CreateUploadParams struct {
	UploadLength   int64          `json:"Upload-Length"`
	UploadMetadata string         `json:"Upload-Metadata"`
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// LookupUsersParams defines parameters for LookupUsers.
type LookupUsersParams struct {
	Q Query `form:"q" json:"q"`
}

// RequestAccessJSONRequestBody defines body for RequestAccess for application/json ContentType.
type RequestAccessJSONRequestBody RequestAccessJSONBody

// AdminUpdatePolicyJSONRequestBody defines body for AdminUpdatePolicy for application/json ContentType.
type AdminUpdatePolicyJSONRequestBody AdminUpdatePolicyJSONBody

// AdminDecideRequestJSONRequestBody defines body for AdminDecideRequest for application/json ContentType.
type AdminDecideRequestJSONRequestBody AdminDecideRequestJSONBody

// AdminUpdateSettingsJSONRequestBody defines body for AdminUpdateSettings for application/json ContentType.
type AdminUpdateSettingsJSONRequestBody AdminUpdateSettingsJSONBody

// AdminStartSupportAccessJSONRequestBody defines body for AdminStartSupportAccess for application/json ContentType.
type AdminStartSupportAccessJSONRequestBody AdminStartSupportAccessJSONBody

// AdminCreateUserJSONRequestBody defines body for AdminCreateUser for application/json ContentType.
type AdminCreateUserJSONRequestBody AdminCreateUserJSONBody

// AdminUpdateUserJSONRequestBody defines body for AdminUpdateUser for application/json ContentType.
type AdminUpdateUserJSONRequestBody AdminUpdateUserJSONBody

// StartMagicAuthJSONRequestBody defines body for StartMagicAuth for application/json ContentType.
type StartMagicAuthJSONRequestBody StartMagicAuthJSONBody

// VerifyMagicAuthJSONRequestBody defines body for VerifyMagicAuth for application/json ContentType.
type VerifyMagicAuthJSONRequestBody VerifyMagicAuthJSONBody

// StartBootstrapJSONRequestBody defines body for StartBootstrap for application/json ContentType.
type StartBootstrapJSONRequestBody StartBootstrapJSONBody

// ValidateBootstrapCodeJSONRequestBody defines body for ValidateBootstrapCode for application/json ContentType.
type ValidateBootstrapCodeJSONRequestBody ValidateBootstrapCodeJSONBody

// VerifyBootstrapJSONRequestBody defines body for VerifyBootstrap for application/json ContentType.
type VerifyBootstrapJSONRequestBody VerifyBootstrapJSONBody

// CreateFolderJSONRequestBody defines body for CreateFolder for application/json ContentType.
type CreateFolderJSONRequestBody CreateFolderJSONBody

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody UpdateMeJSONBody

// UpdatePreferencesJSONRequestBody defines body for UpdatePreferences for application/json ContentType.
type UpdatePreferencesJSONRequestBody UpdatePreferencesJSONBody

// DownloadNodeArchiveJSONRequestBody defines body for DownloadNodeArchive for application/json ContentType.
type DownloadNodeArchiveJSONRequestBody DownloadNodeArchiveJSONBody

// BulkMutateNodesJSONRequestBody defines body for BulkMutateNodes for application/json ContentType.
type BulkMutateNodesJSONRequestBody BulkMutateNodesJSONBody

// UpdateNodeJSONRequestBody defines body for UpdateNode for application/json ContentType.
type UpdateNodeJSONRequestBody UpdateNodeJSONBody

// CopyNodeJSONRequestBody defines body for CopyNode for application/json ContentType.
type CopyNodeJSONRequestBody CopyNodeJSONBody

// MoveNodeJSONRequestBody defines body for MoveNode for application/json ContentType.
type MoveNodeJSONRequestBody MoveNodeJSONBody

// RestoreNodeJSONRequestBody defines body for RestoreNode for application/json ContentType.
type RestoreNodeJSONRequestBody RestoreNodeJSONBody

// SaveSharedFileCopyJSONRequestBody defines body for SaveSharedFileCopy for application/json ContentType.
type SaveSharedFileCopyJSONRequestBody SaveSharedFileCopyJSONBody

// CreatePublicShareJSONRequestBody defines body for CreatePublicShare for application/json ContentType.
type CreatePublicShareJSONRequestBody CreatePublicShareJSONBody

// ExchangePublicCodeJSONRequestBody defines body for ExchangePublicCode for application/json ContentType.
type ExchangePublicCodeJSONRequestBody ExchangePublicCodeJSONBody

// CreateInternalShareJSONRequestBody defines body for CreateInternalShare for application/json ContentType.
type CreateInternalShareJSONRequestBody CreateInternalShareJSONBody

// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody CreateTokenJSONBody
