// Package webassets exposes Arca's compiled React application to the Go server.
package webassets

import "embed"

// Dist contains the complete production frontend generated by pnpm build.
//
//go:embed all:dist
var Dist embed.FS
